name: IITM Caching Submission

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Required Identification Step
      - name: 21f2001357@ds.study.iitm.ac.in
        run: echo "Submission for SKPByahut"

      # Step 1: Cache Setup with the specific key
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-acfa9d2

      # Step 2: The specific step name required by the validator
      - name: prime-cache-acfa9d2
        run: echo "Cache hit status is ${{ steps.cache-step.outputs.cache-hit }}"
